apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hengstey-backyard-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Branchenprimus/hengstey-backyard-platform.git
      targetRevision: 00e2b4d4420c1c69bdecb0d3c3a4abe56535cd8e
      path: deploy/helm/hengstey-backyard
      helm:
        releaseName: hengstey-backyard
        valueFiles:
          - $values/platform/hengstey-backyard-dev/values.yaml
    - repoURL: https://github.com/Branchenprimus/auto-app-deploy
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: hengstey-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
