image:
  repository: ghcr.io/branchenprimus/hengstey-backyard-platform
  tag: "cab95baf67a95e256b4bb3ad2a68a63b0b6b68f6"
imagePullSecrets:
  - name: ghcr-pull
replicaCount: 1
app:
  baseUrl: https://hengstey-backyard-dev.darwin-labs.org
  eventCapacity: 100
  waitlistOfferHours: 72
ingress:
  className: traefik
  host: hengstey-backyard-dev.darwin-labs.org
  tlsEnabled: false
resources:
  requests: {cpu: 50m, memory: 128Mi}
  limits: {cpu: 500m, memory: 384Mi}
postgres:
  storageClassName: local-path
  storageSize: 4Gi
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 384Mi}
minio:
  image: ghcr.io/branchenprimus/hengstey-backyard-minio:bc6328b305b51556a7ef200595c529e35e2c845a
  storageClassName: local-path
  storageSize: 4Gi
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 500m, memory: 384Mi}
jobs:
  backup:
    enabled: false
