name: demo
namespace: apps
replicaCount: 1

image:
  repository: ghcr.io/branchenprimus/demo
  tag: v0.1.0
  pullPolicy: IfNotPresent
  pullSecrets: []

container:
  port: 3000

route:
  host: demo.darwin-labs.org
  path: /

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: []

extraSecretMounts: []

persistence:
  enabled: false
  mountPath: /data
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: ""
