#!/usr/bin/env python3
"""Sync auto-app-deploy apps into Uptime Kuma monitors.

Source of truth: apps/*.yaml in this GitOps repo.
Target: Uptime Kuma SQLite DB inside the Kubernetes deployment.

Why DB sync instead of the Socket.IO API?
- Uptime Kuma's community Socket.IO API needs the web login session/password.
- The API key generated by Uptime Kuma is for protected HTTP API routes, not for
  monitor creation through the Socket.IO admin interface.
- In this homelab setup we control the k3s deployment, so an idempotent DB sync
  followed by a rollout restart is the most deterministic automation path.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Missing dependency: pyyaml. Install with: python -m pip install pyyaml") from exc

REPO_ROOT = Path(__file__).resolve().parents[1]
APPS_DIR = REPO_ROOT / "apps"
DEFAULT_NAMESPACE = "apps"
DEFAULT_DEPLOYMENT = "uptime-kuma"
DEFAULT_DB = "/app/data/kuma.db"

# App-specific health path overrides for services whose route root intentionally
# returns 404 or is not a useful health endpoint.
HEALTH_PATH_OVERRIDES = {
    "gh-issue-pipeline": "/healthz",
}


def run(cmd: list[str], *, input_text: str | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        input=input_text,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=check,
    )


def sql_literal(value: Any) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def load_apps() -> list[dict[str, Any]]:
    apps: list[dict[str, Any]] = []
    for path in sorted(APPS_DIR.glob("*.yaml")):
        data = yaml.safe_load(path.read_text()) or {}
        name = data.get("name") or path.stem
        route = data.get("route") or {}
        host = route.get("host")
        route_path = route.get("path") or "/"
        if not host:
            continue
        monitor_path = HEALTH_PATH_OVERRIDES.get(str(name), route_path)
        if not str(monitor_path).startswith("/"):
            monitor_path = f"/{monitor_path}"
        access = data.get("access") or {}
        apps.append(
            {
                "name": name,
                "host": host,
                "path": monitor_path,
                "access_enabled": bool(access.get("enabled", True)),
                "file": path.name,
            }
        )
    return apps


def monitor_rows(apps: list[dict[str, Any]], *, include_self: bool = True) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for app in apps:
        name = app["name"]
        if not include_self and name == "uptime-kuma":
            continue
        path = app["path"]
        rows.append(
            {
                "group": "Apps - Internal",
                "name": f"{name} internal",
                "url": f"http://{name}.{DEFAULT_NAMESPACE}.svc.cluster.local{path}",
                "description": f"Internal Kubernetes service monitor generated from {app['file']}",
            }
        )
        rows.append(
            {
                "group": "Apps - Public",
                "name": f"{name} public",
                "url": f"https://{app['host']}{path}",
                "description": f"Public Cloudflare/Ingress monitor generated from {app['file']}",
            }
        )
    return rows


def build_sql(rows: list[dict[str, Any]], *, user_id: int = 1, interval: int = 60) -> str:
    groups = sorted({row["group"] for row in rows})
    statements = [
        "PRAGMA foreign_keys=ON;",
        "BEGIN IMMEDIATE;",
    ]

    for group in groups:
        statements.append(
            "INSERT INTO \"group\" (name, public, active, weight) "
            f"SELECT {sql_literal(group)}, 0, 1, 1000 "
            f"WHERE NOT EXISTS (SELECT 1 FROM \"group\" WHERE name={sql_literal(group)});"
        )

    for row in rows:
        name = row["name"]
        url = row["url"]
        desc = row["description"]
        group = row["group"]
        statements.append(
            "INSERT INTO monitor "
            "(name, active, user_id, interval, url, type, weight, maxretries, retry_interval, maxredirects, accepted_statuscodes_json, method, description, timeout) "
            "SELECT "
            f"{sql_literal(name)}, 1, {int(user_id)}, {int(interval)}, {sql_literal(url)}, 'http', 2000, 1, {int(interval)}, 10, "
            f"{sql_literal(json.dumps(['200-399']))}, 'GET', {sql_literal(desc)}, 48 "
            f"WHERE NOT EXISTS (SELECT 1 FROM monitor WHERE name={sql_literal(name)});"
        )
        statements.append(
            "UPDATE monitor SET "
            f"url={sql_literal(url)}, active=1, interval={int(interval)}, retry_interval={int(interval)}, "
            f"accepted_statuscodes_json={sql_literal(json.dumps(['200-399']))}, method='GET', description={sql_literal(desc)}, timeout=48 "
            f"WHERE name={sql_literal(name)};"
        )
        statements.append(
            "INSERT INTO monitor_group (monitor_id, group_id, weight, send_url) "
            "SELECT m.id, g.id, 1000, 1 FROM monitor m, \"group\" g "
            f"WHERE m.name={sql_literal(name)} AND g.name={sql_literal(group)} "
            "AND NOT EXISTS (SELECT 1 FROM monitor_group mg WHERE mg.monitor_id=m.id AND mg.group_id=g.id);"
        )

    statements.extend(["COMMIT;", ""])
    return "\n".join(statements)


def kube_sql(sql: str, *, namespace: str, deployment: str, db_path: str, dry_run: bool) -> None:
    if dry_run:
        print(sql)
        return
    cmd = [
        "sudo",
        "kubectl",
        "-n",
        namespace,
        "exec",
        "-i",
        f"deploy/{deployment}",
        "--",
        "sqlite3",
        db_path,
    ]
    run(cmd, input_text=sql)


def restart(namespace: str, deployment: str, *, dry_run: bool) -> None:
    if dry_run:
        print(f"DRY RUN: would restart deployment/{deployment} in namespace {namespace}")
        return
    run(["sudo", "kubectl", "-n", namespace, "rollout", "restart", f"deployment/{deployment}"])
    out = run(["sudo", "kubectl", "-n", namespace, "rollout", "status", f"deployment/{deployment}", "--timeout=300s"])
    print(out.stdout.strip())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--namespace", default=DEFAULT_NAMESPACE)
    parser.add_argument("--deployment", default=DEFAULT_DEPLOYMENT)
    parser.add_argument("--db-path", default=DEFAULT_DB)
    parser.add_argument("--interval", type=int, default=60, help="Monitor interval in seconds")
    parser.add_argument("--user-id", type=int, default=1, help="Uptime Kuma user_id to own monitors")
    parser.add_argument("--skip-self", action="store_true", help="Do not monitor Uptime Kuma itself")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    apps = load_apps()
    rows = monitor_rows(apps, include_self=not args.skip_self)
    if not rows:
        print("No apps found", file=sys.stderr)
        return 1

    print(f"Discovered {len(apps)} apps; syncing {len(rows)} monitors.")
    sql = build_sql(rows, user_id=args.user_id, interval=args.interval)
    kube_sql(sql, namespace=args.namespace, deployment=args.deployment, db_path=args.db_path, dry_run=args.dry_run)
    restart(args.namespace, args.deployment, dry_run=args.dry_run)
    print("Sync complete.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
