apiVersion: v1
kind: Service
metadata:
  name: {{ include "single-container-webapp.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "single-container-webapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "single-container-webapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
